### ISSUE TITLE
Convert in percentual values

### ISSUE THREAD

**Issue by mj-3101** [mj-3101/interactive-rating-component#1] opened 2023-01-06 00:12 UTC
Different types of values are assigned to the divs (em/rem/px).
To create a more responsive and more readable code, the values have to be changed to percentage.

**Comment by Rishav1707** [comment] 2023-01-06 08:01
Which property you want to change in percentage values?

**Comment by mj-3101** [comment] 2023-01-06 15:30
I thought about replacing re/em values with percentage values so i have one kind of value all over the code. I try to figure out how to make good responsive css without using all kinds of values but i have very little experience in real projects.
Does that make sense?

**Comment by Raghav-Programmer** [comment] 2023-01-06 17:37
if the issue is still open I can do it

**Comment by Rishav1707** [comment] 2023-01-06 17:38
> if the issue is still open I can do it

I am already working..

**Comment by Raghav-Programmer** [comment] 2023-01-06 17:40
oh ok
it was never assigned to anyone that's why I asked

**Closed as completed** 2023-01-10 19:19 UTC
Labels: enhancement, good first issue
